name: Makefile CI

on:
  push:
    branches: [ "main" ]
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

#    - name: Install dependencies
#      run: make depends

    - name: Build
      run: make build
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: output
        # A file, directory or wildcard pattern that describes what to upload
        path: are
