name: Makefile CI

on:
  push:
    branches: [ "main" ]
    

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
    - uses: actions/checkout@v3

#    - name: Install dependencies
#      run: make depends

    - name: Build
      run: make build
      
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: output
        path: ../../out/are
        if-no-files-found: error
